package main

var EnemyDefinitions = map[string]EnemyDefinition{
	"Small Slime": {
		Name: "Small Slime", SpriteSheetX: 0, SpriteSheetY: 2,
		BaseHP: 6, AC: 10, Str: 12, Dex: 10, Con: 11, Int: 8, Wis: 8, Cha: 8, Move: 3,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 0, AttackDiceSize: 0, AttackAbilityMod: "STR",
	},
	"Tough Slime": {
		Name: "Tough Slime", SpriteSheetX: 1, SpriteSheetY: 2,
		BaseHP: 7, AC: 10, Str: 12, Dex: 10, Con: 11, Int: 8, Wis: 8, Cha: 8, Move: 3,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 0, AttackDiceSize: 0, AttackAbilityMod: "STR",
	},
	"Goo Spitter": {
		Name: "Goo Spitter", SpriteSheetX: 2, SpriteSheetY: 2,
		BaseHP: 5, AC: 11, Str: 8, Dex: 14, Con: 10, Int: 8, Wis: 8, Cha: 8, Move: 4,
		Width: 1, Height: 1, AttackType: "ranged", MaxRange: 4,
		AttackDiceNum: 0, AttackDiceSize: 0, AttackAbilityMod: "DEX",
	},
	"Big Slime Boss": {
		Name: "Big Slime Boss", SpriteSheetX: 1, SpriteSheetY: 2,
		BaseHP: 25, AC: 12, Str: 14, Dex: 8, Con: 15, Int: 6, Wis: 6, Cha: 6, Move: 2,
		Width: 2, Height: 2, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 0, AttackDiceSize: 0, AttackAbilityMod: "STR",
	},
	"Melee Skeleton": {
		Name: "Melee Skeleton", SpriteSheetX: 0, SpriteSheetY: 4,
		BaseHP: 13, AC: 13, Str: 10, Dex: 14, Con: 15, Int: 6, Wis: 8, Cha: 5, Move: enemyBaseMovement,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 1, AttackDiceSize: 6, AttackAbilityMod: "DEX",
	},
	"Ranged Skeleton": {
		Name: "Ranged Skeleton", SpriteSheetX: 1, SpriteSheetY: 4,
		BaseHP: 11, AC: 13, Str: 8, Dex: 16, Con: 13, Int: 6, Wis: 8, Cha: 5, Move: enemyBaseMovement,
		Width: 1, Height: 1, AttackType: "ranged", MaxRange: 5,
		AttackDiceNum: 1, AttackDiceSize: 6, AttackAbilityMod: "DEX",
	},
	"Goblin Scout": {
		Name: "Goblin Scout", SpriteSheetX: 2, SpriteSheetY: 0,
		BaseHP: 6, AC: 9, Str: 10, Dex: 15, Con: 10, Int: 10, Wis: 10, Cha: 8, Move: 6,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 1, AttackDiceSize: 4, AttackAbilityMod: "DEX",
	},
	"Goblin Archer": {
		Name: "Goblin Archer", SpriteSheetX: 5, SpriteSheetY: 0,
		BaseHP: 4, AC: 10, Str: 8, Dex: 13, Con: 11, Int: 10, Wis: 12, Cha: 8, Move: 5,
		Width: 1, Height: 1, AttackType: "ranged", MaxRange: 6,
		AttackDiceNum: 1, AttackDiceSize: 6, AttackAbilityMod: "DEX",
	},
	"Goblin Brute": {
		Name: "Goblin Brute", SpriteSheetX: 7, SpriteSheetY: 0,
		BaseHP: 8, AC: 12, Str: 14, Dex: 12, Con: 14, Int: 8, Wis: 8, Cha: 8, Move: 4,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 1, AttackDiceSize: 8, AttackAbilityMod: "STR",
	},
	"Goblin Chieftain": {
		Name: "Goblin Chieftain", SpriteSheetX: 4, SpriteSheetY: 0,
		BaseHP: 30, AC: 15, Str: 17, Dex: 14, Con: 16, Int: 12, Wis: 13, Cha: 14, Move: 4,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 2, AttackDiceSize: 6, AttackAbilityMod: "STR",
	},
	"Goblin Warlock": {
		Name: "Goblin Warlock", SpriteSheetX: 6, SpriteSheetY: 0,
		BaseHP: 10, AC: 11, Str: 8, Dex: 12, Con: 10, Int: 14, Wis: 12, Cha: 12, Move: 4,
		Width: 1, Height: 1, AttackType: "ranged", MaxRange: 5,
		AttackDiceNum: 1, AttackDiceSize: 6, AttackAbilityMod: "INT",
	},
	"Spore Mushroom": {
		Name: "Spore Mushroom", SpriteSheetX: 0, SpriteSheetY: 10,
		BaseHP: 12, AC: 11, Str: 6, Dex: 8, Con: 14, Int: 2, Wis: 10, Cha: 4, Move: 2,
		Width: 1, Height: 1, AttackType: "ranged", MaxRange: 3,
		AttackDiceNum: 1, AttackDiceSize: 4, AttackAbilityMod: "WIS",
	},
	"Elder Spore Mushroom": {
		Name: "Elder Spore Mushroom", SpriteSheetX: 1, SpriteSheetY: 10,
		BaseHP: 40, AC: 13, Str: 8, Dex: 6, Con: 18, Int: 4, Wis: 12, Cha: 6, Move: 1,
		Width: 2, Height: 2, AttackType: "ranged", MaxRange: 4,
		AttackDiceNum: 1, AttackDiceSize: 8, AttackAbilityMod: "CON",
	},
	"Centaur": {
		Name: "Centaur", SpriteSheetX: 3, SpriteSheetY: 7,
		BaseHP: 18, AC: 14, Str: 14, Dex: 16, Con: 14, Int: 10, Wis: 12, Cha: 10, Move: 7,
		Width: 1, Height: 1, AttackType: "ranged", MaxRange: 5,
		AttackDiceNum: 1, AttackDiceSize: 8, AttackAbilityMod: "DEX",
	},
	"Druid": {
		Name: "Druid", SpriteSheetX: 6, SpriteSheetY: 7,
		BaseHP: 14, AC: 12, Str: 8, Dex: 12, Con: 12, Int: 10, Wis: 16, Cha: 12, Move: 4,
		Width: 1, Height: 1, AttackType: "ranged", MaxRange: 4,
		AttackDiceNum: 1, AttackDiceSize: 6, AttackAbilityMod: "WIS",
	},
	"Faun": {
		Name: "Faun", SpriteSheetX: 0, SpriteSheetY: 7,
		BaseHP: 12, AC: 13, Str: 10, Dex: 14, Con: 12, Int: 12, Wis: 14, Cha: 14, Move: 5,
		Width: 1, Height: 1, AttackType: "ranged", MaxRange: 3,
		AttackDiceNum: 1, AttackDiceSize: 6, AttackAbilityMod: "WIS",
	},
	"Dire Wolf": {
		Name: "Dire Wolf", SpriteSheetX: 5, SpriteSheetY: 6,
		BaseHP: 20, AC: 13, Str: 16, Dex: 15, Con: 14, Int: 3, Wis: 12, Cha: 6, Move: 7,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 1, AttackDiceSize: 8, AttackAbilityMod: "STR",
	},
	"Naga": {
		Name: "Naga", SpriteSheetX: 4, SpriteSheetY: 7,
		BaseHP: 22, AC: 15, Str: 14, Dex: 16, Con: 14, Int: 12, Wis: 12, Cha: 14, Move: 4,
		Width: 2, Height: 2, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 1, AttackDiceSize: 8, AttackAbilityMod: "STR",
	},
	"Tauren": {
		Name: "Tauren", SpriteSheetX: 7, SpriteSheetY: 7,
		BaseHP: 45, AC: 15, Str: 18, Dex: 10, Con: 18, Int: 8, Wis: 12, Cha: 10, Move: 4,
		Width: 2, Height: 2, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 2, AttackDiceSize: 8, AttackAbilityMod: "STR",
	},
	"Orc Warrior": {
		Name: "Orc Warrior", SpriteSheetX: 3, SpriteSheetY: 0,
		BaseHP: 18, AC: 15, Str: 18, Dex: 10, Con: 18, Int: 8, Wis: 12, Cha: 10, Move: 4,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 2, AttackDiceSize: 8, AttackAbilityMod: "STR",
	},
	"Orc Shaman": {
		Name: "Orc Shaman", SpriteSheetX: 1, SpriteSheetY: 0,
		BaseHP: 15, AC: 12, Str: 8, Dex: 12, Con: 13, Int: 10, Wis: 15, Cha: 10, Move: 4,
		Width: 1, Height: 1, AttackType: "ranged", MaxRange: 5,
		AttackDiceNum: 1, AttackDiceSize: 8, AttackAbilityMod: "WIS",
	},
	"Orc Chieftain": {
		Name: "Orc Chieftain", SpriteSheetX: 4, SpriteSheetY: 0,
		BaseHP: 18, AC: 15, Str: 18, Dex: 10, Con: 18, Int: 8, Wis: 12, Cha: 10, Move: 4,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 2, AttackDiceSize: 8, AttackAbilityMod: "STR",
	},
	"Orc Brute": {
		Name: "Orc Brute", SpriteSheetX: 0, SpriteSheetY: 0,
		BaseHP: 18, AC: 15, Str: 18, Dex: 10, Con: 18, Int: 8, Wis: 12, Cha: 10, Move: 4,
		Width: 1, Height: 1, AttackType: "melee", MaxRange: 1,
		AttackDiceNum: 2, AttackDiceSize: 8, AttackAbilityMod: "STR",
	},
}

var ClassDefinitions = map[string]*ClassDefinition{
	"Fighter": {
		Name:             "Fighter",
		HitDieSize:       10,
		PrimaryAbility:   "STR",
		SavingThrowProfs: []string{"STR", "CON"},
		SpriteSheetX:     1,
		SpriteSheetY:     1,
		ClassActions: map[string]*ClassAction{
			"second_wind": {
				ActionID:      "second_wind",
				Name:          "Second Wind",
				RequiredLevel: 2,
				ActionType:    ActionTypeStandard,
				ResourceType:  ResourceClassFeature,
				ResourceCost:  1,
				UsesPerRest:   1,
				RefreshesOn:   RestTypeNever,
				Description:   "Use Action: Heal using 1 Hit Die (d10 + CON).",
			},
			"action_surge": {
				ActionID:      "action_surge",
				Name:          "Action Surge",
				RequiredLevel: 2,
				ActionType:    ActionTypeFree,
				ResourceType:  ResourceClassFeature,
				ResourceCost:  1,
				UsesPerRest:   1,
				RefreshesOn:   RestTypeNever,
				Description:   "Gain an additional standard action this turn.",
			},
			"shove": {
				ActionID:      "shove",
				Name:          "Shove",
				RequiredLevel: 2,
				ActionType:    ActionTypeStandard,
				ResourceType:  ResourceNone,
				ResourceCost:  0,
				UsesPerRest:   0,
				RefreshesOn:   RestTypeNever,
				Description:   "Push an adjacent enemy 1 tile away.",
			},
			"riposte": {
				ActionID:      "riposte",
				Name:          "Riposte",
				RequiredLevel: 3,
				ActionType:    ActionTypeReaction,
				ResourceType:  ResourceNone,
				ResourceCost:  0,
				UsesPerRest:   0,
				RefreshesOn:   RestTypeNever,
				Description:   "Reaction: Attack back when an enemy misses you.",
			},
		},
	},
	"Mage": {
		Name:             "Mage",
		HitDieSize:       6,
		PrimaryAbility:   "INT",
		SavingThrowProfs: []string{"INT", "WIS"},
		SpriteSheetX:     0,
		SpriteSheetY:     4,
		ClassActions: map[string]*ClassAction{
			"arcane_recovery": {
				ActionID:      "arcane_recovery",
				Name:          "Arcane Recovery",
				RequiredLevel: 2,
				ActionType:    ActionTypeFree,
				ResourceType:  ResourceClassFeature,
				ResourceCost:  1,
				UsesPerRest:   1,
				RefreshesOn:   RestTypeLong,
				Description:   "Once per long rest cycle, recover spell slots during a short rest.",
			},
			"teleport": {
				ActionID:      "teleport",
				Name:          "Teleport",
				RequiredLevel: 2,
				ActionType:    ActionTypeStandard,
				ResourceType:  ResourceNone,
				ResourceCost:  0,
				UsesPerRest:   0,
				RefreshesOn:   RestTypeNever,
				Description:   "Swap positions with an adjacent enemy.",
			},
		},
	},
}

var ActionTable map[string]*ActionDefinition

func init() {
	ActionTable = map[string]*ActionDefinition{
		"melee_attack": {
			ID:               "melee_attack",
			Name:             "Melee Attack",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetEnemyAdjacent,
			Range:            1,
			RequiresTarget:   true,
			Execute:          executeMeleeAttack,
			VisualEffectType: "Default",
		},
		"ranged_attack": {
			ID:               "ranged_attack",
			Name:             "Ranged Attack",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetEnemyRange,
			Range:            playerRangedRange,
			RequiresTarget:   true,
			Execute:          executeRangedAttack,
			VisualEffectType: "Default",
		},
		"quick_strike": {
			ID:               "quick_strike",
			Name:             "Quick Strike",
			ActionType:       ActionTypeBonus,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetEnemyAdjacent,
			Range:            1,
			RequiresTarget:   true,
			Execute:          executeQuickStrike,
			VisualEffectType: "Default",
		},
		"stunning_strike": {
			ID:               "stunning_strike",
			Name:             "Stunning Strike",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetEnemyAdjacent,
			Range:            1,
			RequiresTarget:   true,
			Execute:          executeStunningStrike,
			VisualEffectType: "Default",
		},
		"dash": {
			ID:               "dash",
			Name:             "Dash",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetSelf,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeDash,
			VisualEffectType: "Default",
		},
		"disengage": {
			ID:               "disengage",
			Name:             "Disengage",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetSelf,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeDisengage,
			VisualEffectType: "Default",
		},
		"wait": {
			ID:               "wait",
			Name:             "Wait (End Turn)",
			ActionType:       ActionTypeFree,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetNone,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeWait,
			VisualEffectType: "None",
		},
		"second_wind": {
			ID:               "second_wind",
			Name:             "Second Wind",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceClassFeature,
			ResourceCost:     1,
			Targeting:        TargetSelf,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeSecondWind,
			VisualEffectType: "Heal",
		},
		"action_surge": {
			ID:               "action_surge",
			Name:             "Action Surge",
			ActionType:       ActionTypeFree,
			ResourceType:     ResourceClassFeature,
			ResourceCost:     1,
			Targeting:        TargetSelf,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeActionSurge,
			VisualEffectType: "Default",
		},
		"firebolt": {
			ID:               "firebolt",
			Name:             "Firebolt",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetEnemyRange,
			Range:            playerRangedRange + 2,
			RequiresTarget:   true,
			Execute:          executeFirebolt,
			VisualEffectType: "Fire",
		},
		"arcane_recovery": {
			ID:               "arcane_recovery",
			Name:             "Arcane Recovery",
			ActionType:       ActionTypeFree,
			ResourceType:     ResourceClassFeature,
			ResourceCost:     1,
			Targeting:        TargetSelf,
			Range:            0,
			RequiresTarget:   false,
			Execute:          nil,
			VisualEffectType: "None",
		},
		"magic_missile": {
			ID:               "magic_missile",
			Name:             "Magic Missile",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetEnemyRange,
			Range:            playerRangedRange + 2,
			RequiresTarget:   true,
			Execute:          executeMagicMissile,
			VisualEffectType: "Force",
		},
		"shield": {
			ID:               "shield",
			Name:             "Shield",
			ActionType:       ActionTypeReaction,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetSelf,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeShield,
			VisualEffectType: "Arcane",
		},
		"arcane_blink": {
			ID:               "arcane_blink",
			Name:             "Arcane Blink",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetEmptyTile,
			Range:            playerBaseMovement,
			RequiresTarget:   true,
			Execute:          executeArcaneBlink,
			VisualEffectType: "Arcane",
		},
		"burning_hands": {
			ID:               "burning_hands",
			Name:             "Burning Hands",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetSelf,
			Range:            1,
			RequiresTarget:   false,
			Execute:          executeBurningHands,
			VisualEffectType: "Fire",
		},
		"frost_nova": {
			ID:               "frost_nova",
			Name:             "Frost Nova",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetSelf,
			Range:            1,
			RequiresTarget:   false,
			Execute:          executeFrostNova,
			VisualEffectType: "Cold",
		},
		"mind_spike": {
			ID:               "mind_spike",
			Name:             "Mind Spike",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetEnemyRange,
			Range:            playerRangedRange,
			RequiresTarget:   true,
			Execute:          executeMindSpike,
			VisualEffectType: "Psychic",
		},
		"ray_of_frost": {
			ID:               "ray_of_frost",
			Name:             "Ray of Frost",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetEnemyRange,
			Range:            playerRangedRange + 1,
			RequiresTarget:   true,
			Execute:          executeRayOfFrost,
			VisualEffectType: "Cold",
		},
		"shocking_grasp": {
			ID:               "shocking_grasp",
			Name:             "Shocking Grasp",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetEnemyAdjacent,
			Range:            1,
			RequiresTarget:   true,
			Execute:          executeShockingGrasp,
			VisualEffectType: "Default",
		},

		"magic_armor": {
			ID:               "magic_armor",
			Name:             "Magic Armor",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetSelf,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeMagicArmor,
			VisualEffectType: "Arcane",
		},
		"elemental_strike": {
			ID:               "elemental_strike",
			Name:             "Elemental Strike",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetEnemyRange,
			Range:            playerRangedRange,
			RequiresTarget:   true,
			Execute:          executeElementalStrike,
			VisualEffectType: "Default",
		},
		"feather_fall": {
			ID:               "feather_fall",
			Name:             "Feather Fall",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetSelf,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeFeatherFall,
			VisualEffectType: "Default",
		},
		"expeditious_retreat": {
			ID:               "expeditious_retreat",
			Name:             "Expeditious Retreat",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceSpellSlotL1,
			ResourceCost:     1,
			Targeting:        TargetSelf,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeExpeditiousRetreat,
			VisualEffectType: "Default",
		},
		"accept_defeat": {
			ID:               "accept_defeat",
			Name:             "Accept Defeat (Quit Game)",
			ActionType:       ActionTypeFree,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetNone,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeQuitGame,
			VisualEffectType: "None",
		},
		"shove": {
			ID:               "shove",
			Name:             "Shove",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetEnemyAdjacent,
			Range:            1,
			RequiresTarget:   true,
			Execute:          executeShove,
			VisualEffectType: "Default",
		},
		"riposte": {
			ID:               "riposte",
			Name:             "Riposte",
			ActionType:       ActionTypeReaction,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetNone,
			Range:            0,
			RequiresTarget:   false,
			Execute:          executeRiposte,
			VisualEffectType: "Default",
		},
		"teleport": {
			ID:               "teleport",
			Name:             "Teleport",
			ActionType:       ActionTypeStandard,
			ResourceType:     ResourceNone,
			ResourceCost:     0,
			Targeting:        TargetEnemyAdjacent,
			Range:            1,
			RequiresTarget:   true,
			Execute:          executeTeleport,
			VisualEffectType: "Arcane",
		},
	}
}
